feature: add email verification
BalancyTeam/balancy-app-backend pull request #37
Opened 2023-06-16 18:08 UTC by cropup

2023-06-16 18:42 UTC, Evcat6 requested changes

2023-06-16 18:42 UTC, Evcat6 commented on src/common/services/email.service.ts
> +        console.log(`Email sent to ${email}: ` + info.response);
we can use there nest logger service from `src/common/index.ts`

2023-06-17 10:24 UTC, cropup commented on src/common/services/email.service.ts
> +        console.log(`Email sent to ${email}: ` + info.response);
Fixed it. Thank you

2023-06-17 11:37 UTC, Evcat6 approved these changes

2023-06-17 11:37 UTC, merged