Feature/tasks
BalancyTeam/balancy-app-backend pull request #47
Opened 2023-06-21 19:57 UTC by Nataliya1508

2023-06-22 04:08 UTC, Evcat6 commented
I think you should rewrite `src/tasks/tipes/tipesResponse.interface.ts` to `src/tasks/types/types-response.interface.ts`

2023-06-22 07:16 UTC, Evcat6 requested changes

2023-06-22 07:16 UTC, Evcat6 commented on src/tasks/tipes/tipesResponse.interface.ts
> +export interface TaskResponseInterface {
I recommend to name it `ITaskResponse`

2023-06-22 08:56 UTC, cropup commented on src/users/entities/user.entity.ts
> +export class UserEntity {
Why to change default naming convention?

2023-06-22 08:57 UTC, cropup commented on src/users/users.service.ts
> +  private async findUserBy(payload: Partial<any>) {
This type doesn't make sense. Replace it with something reasonable.

2023-06-22 08:59 UTC, cropup commented on src/tasks/entities/task.entity.ts
> +  username: UserEntity;
Maybe `user`, instead of `username`?

2023-06-22 12:28 UTC, Evcat6 commented on src/users/users.service.ts
> +  private async findUserBy(payload: Partial<any>) {
i recommend to use `unknwon` type

2023-06-22 17:05 UTC, Evcat6 commented on src/tasks/tipes/tipesResponse.interface.ts
> +export interface TaskResponseInterface {
I think you can create Dto istead of interface maybe `GetTaskResponseDto` in `dto` folder and it will be automatically added to our docs in `/api-docs` route

2023-06-22 17:08 UTC, cropup commented on src/users/users.service.ts
> +  private async findUserBy(payload: Partial<any>) {
> i recommend to use `object` type

Why doesn't the old `Partial<User>` fit?

2023-06-23 09:34 UTC, Nataliya1508 commented on src/tasks/tipes/tipesResponse.interface.ts
> +export interface TaskResponseInterface {
I fixed my mistake in types. 
Renamed TaskResponseInterface to ITaskResponse. 
If it is possible, while I will leave the Interface. I'll do some refactoring later.

2023-06-23 11:00 UTC, cropup requested changes

2023-06-23 11:00 UTC, cropup commented on src/users/users.service.ts
> +  private async findUserBy(payload: Partial<any>) {
Don't forget to change the type

2023-06-26 07:49 UTC, Evcat6 approved these changes

2023-06-26 07:50 UTC, cropup approved these changes

2023-06-26 11:47 UTC, merged